/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "Library/STD_TYPES.h"
#include "Library/BIT_MATHS.h"
#include "MCAL/RCC/RCC_Interface.h"
#include "MCAL/GPIO/GPIO_Interface.h"
#include "MCAL/SYSTICK/Systick_Interface.h"
#include "HAL/LCD/LCD.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



int main(void)
{

	MRCC_setSystemClk(CLK_HSI);
	MRCC_setClockSts(CLK_HSI, ENABLE);
	MRCC_APB2_EnablePeripheralClk(_GPIOA);
	MRCC_APB2_EnablePeripheralClk(_GPIOB);
	MRCC_APB2_EnablePeripheralClk(_GPIOC);

	SysTick_Init(10);
	//LCD_Init();


	GPIO_PinConfig_t  pinConfigLed1={
		.port= PORTA,
		.PinNum= PIN2,
		.Mode =OUTPUT_2MHZ,
		.OutputType=  OP_PUSH_PULL
	};

	GPIO_u8PinInit(&pinConfigLed1);

	GPIO_PinConfig_t  pinConfigRed2={
		.port= PORTA,
		.PinNum= PIN1,
		.Mode =OUTPUT_2MHZ,
		.OutputType=  OP_PUSH_PULL
	};

	GPIO_u8PinInit(&pinConfigRed2);



	GPIO_PinConfig_t  pinConfigLed3={
			.port= PORTC,
			.PinNum= PIN15,
			.Mode =OUTPUT_2MHZ,
			.OutputType=  OP_PUSH_PULL
		};

		GPIO_u8PinInit(&pinConfigLed3);


	GPIO_PinConfig_t  pinConfigLed4={
				.port= PORTC,
				.PinNum= PIN14,
				.Mode =OUTPUT_2MHZ,
				.OutputType=  OP_PUSH_PULL
			};

			GPIO_u8PinInit(&pinConfigLed4);

	GPIO_PinConfig_t  pinConfigLed5={
				.port= PORTC,
				.PinNum= PIN13,
				.Mode =OUTPUT_2MHZ,
				.OutputType=  OP_PUSH_PULL
			};

			GPIO_u8PinInit(&pinConfigLed5);

    /* Loop forever */
	while(1)
	{
		GPIO_u8SetPinValue(PORTA, PIN1, HIGH);
		GPIO_u8SetPinValue(PORTA, PIN2, HIGH);
		GPIO_u8SetPinValue(PORTC, PIN13, HIGH);
		GPIO_u8SetPinValue(PORTC, PIN14, HIGH);
		GPIO_u8SetPinValue(PORTC, PIN15, HIGH);
		SysTick_voidBusyWait_ms(10000);
		GPIO_u8SetPinValue(PORTA, PIN1, LOW);
		GPIO_u8SetPinValue(PORTA, PIN2, LOW);
		GPIO_u8SetPinValue(PORTC, PIN13, LOW);
		GPIO_u8SetPinValue(PORTC, PIN14, LOW);
		GPIO_u8SetPinValue(PORTC, PIN15, LOW);
        SysTick_voidBusyWait_ms(10000);


	}
}
